name: Math Functions Tests

on:
    push:
        branches:
            - '*'   # For all branches.

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./tests/
        
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12']
        
        steps:
            - name: Checking Out Branch
              uses: actions/checkout@v3

            - name: Setting up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            
            - name: Testing Math Utils
              run: python ./test_math.py
